apiVersion: v1
kind: Service
metadata:
  name: activemq
  labels:
    name: activemq
spec:
  type: NodePort
  ports:
  - port: 61612
    targetPort: 61612
  - port: 8161
    targetPort: 8161
  selector:
    role: activemq