kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus
  namespace: monitoring
spec:
  accessModes:
     - ReadWriteOnce
  storageClassName: ceph-db
  resources:
    requests:
      storage: 200G

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana
  namespace: monitoring
spec:
  accessModes:
     - ReadWriteOnce
  storageClassName: ceph-db
  resources:
    requests:
      storage: 200G