CREATE TABLE `est_import_error_data` (
  `log_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '数据ID，主键，自增',
  `impt_id` int(11) NOT NULL DEFAULT '0' COMMENT '导入批次号',
  `cle_name` varchar(50) NOT NULL COMMENT '客户姓名【客户信息】',
  `cle_pingyin` varchar(50) NOT NULL COMMENT '客户名称拼音【客户信息】',
  `cle_dial_number` int(11) NOT NULL DEFAULT '0' COMMENT '通话次数(拨打次数)',
  `cle_phone` varchar(20) NOT NULL COMMENT '客户电话【客户信息】',
  `cle_phone2` varchar(20) NOT NULL DEFAULT '' COMMENT 'åŠžå…¬ç”µè¯',
  `cle_phone3` varchar(20) NOT NULL DEFAULT '' COMMENT 'å…¶ä»–ç”µè¯',
  `cle_province_id` int(11) NOT NULL DEFAULT '0' COMMENT '省ID【客户信息】',
  `cle_province_name` varchar(20) NOT NULL COMMENT '省【客户信息】',
  `cle_city_id` int(11) NOT NULL DEFAULT '0' COMMENT '市ID【客户信息】',
  `cle_city_name` varchar(20) NOT NULL COMMENT '市【客户信息】',
  `cle_area_id` int(11) NOT NULL DEFAULT '0' COMMENT '区ID【客户信息】',
  `cle_area` varchar(10) NOT NULL COMMENT '区【客户信息】',
  `cle_address` varchar(100) NOT NULL COMMENT '详细地址【客户信息】',
  `cle_info_source` varchar(20) NOT NULL COMMENT '信息来源【客户信息】',
  `cle_stage` varchar(20) NOT NULL COMMENT '客户阶段（数据字典配置）【客户信息】',
  `cle_chance` varchar(5) NOT NULL COMMENT '成交几率【客户信息】',
  `cle_expected_time` date NOT NULL COMMENT '预计成交时间【客户信息】',
  `cle_stat` varchar(20) NOT NULL COMMENT '客户状态：待打、有效、无效、无法接通、号码错误【客户信息】',
  `cle_remark` text NOT NULL COMMENT '备注【客户信息】',
  `cle_1` text,
  `cle_2` varchar(50) NOT NULL COMMENT '配置字段2【客户信息】',
  `cle_3` text,
  `cle_4` text,
  `cle_5` text,
  `cle_6` text,
  `cle_7` text,
  `cle_8` varchar(50) NOT NULL COMMENT '配置字段8【客户信息】',
  `cle_9` varchar(50) NOT NULL COMMENT '配置字段9【客户信息】',
  `cle_10` varchar(50) NOT NULL COMMENT '配置字段10【客户信息】',
  `cle_11` varchar(50) NOT NULL COMMENT '配置字段11【客户信息】',
  `cle_12` varchar(50) NOT NULL COMMENT '配置字段12【客户信息】',
  `cle_first_connecttime` date NOT NULL COMMENT '首次联系时间',
  `cle_last_connecttime` date NOT NULL COMMENT '最近一次联系时间',
  `con_rec_next_time` date NOT NULL COMMENT '下次联系时间',
  `user_id` int(11) DEFAULT '0',
  `dept_id` int(11) NOT NULL DEFAULT '0' COMMENT '数据所属部门：0表示公司数据 不分部门',
  `cle_executor_time` datetime NOT NULL COMMENT '分配或占有时间',
  `cle_creat_time` date NOT NULL COMMENT '创建时间',
  `cle_creat_user_id` int(11) NOT NULL DEFAULT '0' COMMENT '创建者ID',
  `impt_error_remark` text NOT NULL COMMENT '导入备注',
  `cle_1_1` text NOT NULL,
  `cle_1_2` text NOT NULL,
  `cle_1_3` text NOT NULL,
  `cle_8_1` text NOT NULL,
  `cle_8_2` text NOT NULL,
  `cle_8_3` text NOT NULL,
  `cle_13` text,
  `cle_14` text,
  `cle_15` varchar(50) NOT NULL DEFAULT '',
  `cle_16` varchar(50) NOT NULL DEFAULT '',
  `cle_17` varchar(50) NOT NULL DEFAULT '',
  `cle_18` varchar(50) NOT NULL DEFAULT '',
  `cle_19` varchar(50) NOT NULL DEFAULT '',
  `cle_20` varchar(50) NOT NULL DEFAULT '',
  `cle_21` varchar(50) NOT NULL DEFAULT '',
  `cle_22` varchar(50) NOT NULL DEFAULT '',
  `cle_23` varchar(50) NOT NULL DEFAULT '',
  `cle_24` varchar(50) NOT NULL DEFAULT '',
  `cle_25` varchar(50) NOT NULL DEFAULT '',
  `cle_26` varchar(50) NOT NULL DEFAULT '',
  `cle_5_1` text,
  `cle_5_2` text,
  `cle_5_3` text,
  `cle_6_1` text,
  `cle_6_2` text,
  `cle_6_3` text,
  `cle_10_1` text,
  `cle_10_2` text,
  `cle_10_3` text,
  `cle_12_1` text,
  `cle_12_2` text,
  `cle_12_3` text,
  `cle_27` varchar(50) NOT NULL DEFAULT '',
  `cle_28` varchar(50) NOT NULL DEFAULT '',
  `cle_14_1` text,
  `cle_14_2` text,
  `cle_14_3` text,
  `cle_28_1` text,
  `cle_28_2` text,
  `cle_28_3` text,
  `cle_26_1` text,
  `cle_26_2` text,
  `cle_26_3` text,
  `cle_29` varchar(50) NOT NULL DEFAULT '',
  `cle_30` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`log_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='记录导入过程中的不合法数据'