CREATE TABLE `est_statistics_stage` (
  `deal_date` date NOT NULL COMMENT '处理时间',
  `user_id` int(11) NOT NULL DEFAULT '0' COMMENT '处理坐席',
  `dept_id` int(11) NOT NULL DEFAULT '0',
  `conn_secs` int(11) NOT NULL DEFAULT '0' COMMENT '通话时长',
  `conn_num` int(11) NOT NULL DEFAULT '0' COMMENT '通话数：呼入/呼出（接通/未接通）',
  `conn_success` int(11) NOT NULL DEFAULT '0' COMMENT '坐席呼通量：呼入/呼出',
  `conn_success_out` int(11) NOT NULL DEFAULT '0' COMMENT '坐席呼出接通量',
  `conn_out_num` int(11) NOT NULL DEFAULT '0' COMMENT '坐席呼出量',
  `conn_success_in` int(11) NOT NULL DEFAULT '0' COMMENT '坐席呼入接通量',
  `conn_in_num` int(11) NOT NULL DEFAULT '0' COMMENT '坐席呼入量',
  `transformation` int(11) NOT NULL DEFAULT '0' COMMENT '转化量',
  `new_increment` int(11) NOT NULL DEFAULT '0' COMMENT '新增客户量',
  `recede_num` int(11) DEFAULT '0' COMMENT '退化量',
--   `cle_stage_106647` int(11) DEFAULT '0',
--   `cle_stage_106648` int(11) DEFAULT '0',
--   `cle_stage_106649` int(11) DEFAULT '0',
--   `cle_stage_11` int(11) DEFAULT '0',
--   `cle_stage_12` int(11) DEFAULT '0',
--   `cle_stage_13` int(11) DEFAULT '0',
--   `cle_stage_14` int(11) DEFAULT '0',
--   `cle_stage_15` int(11) DEFAULT '0',
--   `cle_stage_34` int(11) DEFAULT '0',
  PRIMARY KEY (`deal_date`,`user_id`),
  KEY `dept_id` (`dept_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='工作量统计：通话统计+业务统计'