CREATE TABLE `est_order` (
  `order_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '订单id',
  `order_num` varchar(20) NOT NULL DEFAULT '' COMMENT '订单编号',
  `cle_id` int(11) NOT NULL COMMENT '客户id',
  `cle_name` varchar(20) DEFAULT '' COMMENT '客户名称',
  `cle_phone` varchar(20) DEFAULT '' COMMENT '客户电话',
  `cle_address` varchar(200) DEFAULT '' COMMENT '客户地址',
  `order_price` decimal(10,2) NOT NULL COMMENT '订单总价',
  `order_state` varchar(20) NOT NULL DEFAULT '' COMMENT '订单状态 （数据字典配置）【订单信息】',
  `order_remark` text COMMENT '备注',
  `user_id` int(11) NOT NULL COMMENT '所属人',
  `dept_id` int(11) NOT NULL COMMENT '所属部门',
  `order_accept_time` datetime NOT NULL COMMENT '下单时间',
  `order_delivery_number` varchar(30) DEFAULT '' COMMENT '配送单号',
  `order_delivery_mode` varchar(20) DEFAULT '' COMMENT '配送方式',
  `con_name` varchar(20) DEFAULT '' COMMENT '联系人',
  `con_mobile` varchar(20) DEFAULT '' COMMENT '联系人电话',
  `order_1` text,
  `order_2` varchar(50) NOT NULL DEFAULT '',
  `order_3` varchar(50) NOT NULL DEFAULT '',
  `order_4` varchar(50) NOT NULL DEFAULT '',
  `order_5` varchar(50) NOT NULL DEFAULT '',
  `order_6` varchar(50) NOT NULL DEFAULT '',
  `order_9` varchar(50) NOT NULL DEFAULT '',
  `order_10` varchar(50) NOT NULL DEFAULT '',
  `order_11` varchar(50) NOT NULL DEFAULT '',
  `order_12` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`order_id`),
  UNIQUE KEY `order_num` (`order_num`),
  KEY `dept_id` (`dept_id`),
  KEY `user_id` (`user_id`),
  KEY `order_accept_time` (`order_accept_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='订单表'