CREATE TABLE `est_service` (
  `serv_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键，自增',
  `serv_theme` varchar(100) NOT NULL DEFAULT '' COMMENT '主题',
  `serv_type` varchar(20) NOT NULL DEFAULT '' COMMENT '服务类型',
  `cle_id` int(11) NOT NULL DEFAULT '0' COMMENT '对应客户ID',
  `cle_name` varchar(50) NOT NULL DEFAULT '' COMMENT '客户名称',
  `cle_phone` varchar(20) NOT NULL DEFAULT '' COMMENT '客户电话',
  `con_name` varchar(20) NOT NULL DEFAULT '' COMMENT '联系人姓名',
  `con_mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '联系人电话',
  `serv_state` varchar(20) NOT NULL DEFAULT '' COMMENT '服务状态：无需处理  未处理  处理中  处理完成',
  `dept_id` int(11) NOT NULL DEFAULT '0' COMMENT '转交部门',
  `user_id` int(11) NOT NULL DEFAULT '0' COMMENT '转交人',
  `serv_deal_time` int(11) NOT NULL DEFAULT '0' COMMENT '处理时间',
  `serv_content` text NOT NULL COMMENT '内容',
  `serv_remark` text NOT NULL COMMENT '备注',
  `serv_accept_time` int(11) NOT NULL DEFAULT '0' COMMENT '受理时间',
  `create_user_id` int(11) NOT NULL DEFAULT '0' COMMENT '受理人',
  `update_user_id` int(11) NOT NULL DEFAULT '0' COMMENT '更新人',
  `serv_1` varchar(50) NOT NULL DEFAULT '',
  `serv_2` text,
  `serv_5` varchar(50) NOT NULL DEFAULT '',
  `serv_6` varchar(50) NOT NULL DEFAULT '',
  `serv_7` varchar(50) NOT NULL DEFAULT '',
  `serv_8` varchar(50) NOT NULL DEFAULT '',
  `call_id` varchar(32) NOT NULL DEFAULT '0' COMMENT '呼叫ID',
  `serv_1_1` text,
  `serv_1_2` text,
  `serv_1_3` text,
  `serv_9` varchar(50) NOT NULL DEFAULT '',
  `serv_10` varchar(50) NOT NULL DEFAULT '',
  `serv_11` varchar(50) NOT NULL DEFAULT '',
  `serv_12` varchar(50) NOT NULL DEFAULT '',
  `serv_13` varchar(50) NOT NULL DEFAULT '',
  `serv_14` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`serv_id`),
  KEY `cle_id` (`cle_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='客服服务'