CREATE TABLE `est_users` (
  `user_id` int(11) NOT NULL COMMENT '员工id',
  `user_num` varchar(64) DEFAULT '' COMMENT '工号',
  `ag_nickname` varchar(32) DEFAULT '' COMMENT '坐席昵称',
  `user_name` varchar(64) DEFAULT '' COMMENT '姓名',
  `user_password` varchar(64) DEFAULT '' COMMENT '密码',
  `user_phone` varchar(20) DEFAULT '' COMMENT '坐席电话',
  `user_ol_model` tinyint(1) DEFAULT NULL COMMENT '长接通模式：0不用长接通、1长接通、2长接通并自动接听',
  `role_id` int(11) DEFAULT '0' COMMENT '角色',
  `role_name` varchar(100) DEFAULT NULL,
  `role_type` tinyint(1) unsigned NOT NULL COMMENT '角色类型',
  `dept_id` int(11) DEFAULT '1' COMMENT '部门',
  `dept_name` varchar(100) DEFAULT '' COMMENT '部门名称',
  `group_id` int(11) DEFAULT '0' COMMENT '业务组ID',
  `user_tel_server` varchar(20) DEFAULT NULL COMMENT '通讯服务器(SIP网关)',
  `user_cti_server` varchar(20) DEFAULT NULL COMMENT '中间件服务器',
  `user_channel` varchar(5) DEFAULT '0',
  `user_sms_phone` varchar(20) NOT NULL DEFAULT '' COMMENT '短信提醒号码',
  `user_if_tip` tinyint(4) NOT NULL DEFAULT '1' COMMENT '来电/客户挂机，右下角弹出提示窗口;0默认，1是，2否',
  `user_remark` text,
  `user_last_login` datetime DEFAULT NULL COMMENT '最后登录时间',
  `user_phone_type` tinyint(4) NOT NULL DEFAULT '3' COMMENT '话机类型 1自动 2软电话 3话机',
  `user_last_ip` varchar(20) DEFAULT '' COMMENT '最后登录ip',
  `user_outcaller_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '外呼主叫号码类型 0全部  1指定 ',
  `user_outcaller_num` varchar(15) NOT NULL DEFAULT '' COMMENT '指定的外呼主叫',
  `user_notebook` text NOT NULL COMMENT '记事本',
  `user_login_state` tinyint(4) NOT NULL DEFAULT '1' COMMENT '坐席登录状态  0默认1空闲 2忙碌',
  `user_workbench_layout` varchar(150) DEFAULT NULL COMMENT '工作桌面div布局',
  `user_display_dialpanel` tinyint(4) NOT NULL DEFAULT '2' COMMENT '是否显示外呼窗口 0默认 1是2否',
  `user_outcall_popup` tinyint(4) NOT NULL DEFAULT '2' COMMENT '外呼弹屏 0默认 1是 2否',
  `user_to_selfphone` tinyint(4) NOT NULL DEFAULT '1' COMMENT '转手机功能 1关闭 2开启',
  `client_list_display` varchar(150) NOT NULL DEFAULT '2,4,10,18,16' COMMENT '客户排序',
  `contact_list_display` varchar(150) NOT NULL DEFAULT '38,39,40' COMMENT '联系人排序',
  `resource_list_display` varchar(150) NOT NULL DEFAULT '2,4,10,18,16' COMMENT '资源排序',
  `product_list_display` varchar(150) NOT NULL DEFAULT '52,53,54,55' COMMENT '产品列表显示',
  `datadeal_list_display` varchar(150) NOT NULL DEFAULT '2,4,10,18,16' COMMENT '数据处理列表显示',
  `order_list_display` varchar(150) NOT NULL DEFAULT '70,71,72,74,75' COMMENT '订单列表显示',
  `service_list_display` varchar(150) NOT NULL DEFAULT '79,80,81,85,86,90' COMMENT '客服服务列表显示',
  `pro_id` int(11) DEFAULT NULL COMMENT '任务id',
  `max_transfer_num` int(11) NOT NULL DEFAULT '0' COMMENT '最大的转接数量',
  `wechat_auth` tinyint(1) NOT NULL DEFAULT '0' COMMENT '会话权限 1.开启 0.关闭',
  `wechat_nickname` varchar(50) DEFAULT NULL COMMENT '昵称',
  `wechat_max_chats` tinyint(4) DEFAULT NULL COMMENT '会话上限',
  `wechat_welcome_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '接通欢迎消息 1.开启 0.关闭',
  `wechat_welcome_message` text COMMENT '接通坐席时欢迎消息',
  `switch_welcome_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '转接欢迎消息 1.开启 0.关闭',
  `switch_welcome_message` text COMMENT '转接坐席时欢迎消息',
  `wechat_noreply_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '无应答回复 1.开启 0.关闭',
  `wechat_serv_noreply_time` int(11) DEFAULT NULL COMMENT '无应答回复时间',
  `wechat_serv_noreply_message` text COMMENT '无应答回复消息',
  `wechat_end_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '会话结束回复 1.开启 0.关闭',
  `wechat_end_message` text COMMENT '会话结束消息',
  `wechat_client_id` int(11) DEFAULT NULL,
  `wechat_dispatch_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  KEY `user_num` (`user_num`),
  KEY `user_name` (`user_name`),
  KEY `role_type` (`role_type`),
  KEY `user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';

ALTER TABLE `est_users`
ADD COLUMN `max_sessions`  tinyint(4) NOT NULL DEFAULT 30 COMMENT '最大会话数（1-100）' AFTER `service_list_display`,
ADD COLUMN `avatar`  varchar(300) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '头像地址' AFTER `max_sessions`,
ADD COLUMN `imid`  varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT 'im系统的唯一ID标识' AFTER `avatar`;
ALTER TABLE `est_users` CHANGE `dept_name` `dept_name` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '公司' COMMENT '部门名称';

