CREATE TABLE `est_project` (
  `pro_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `vcc_id` int(10) NOT NULL DEFAULT '0' COMMENT '企业id',
  `pro_name` varchar(200) NOT NULL COMMENT '任务名称',
  `pro_task` varchar(100) NOT NULL COMMENT '任务数据表名或接口地址',
  `pro_caller` varchar(25) NOT NULL COMMENT '外呼主叫显示',
  `pro_prefix` varchar(20) NOT NULL COMMENT '外呼被叫前缀',
  `pro_lineuse` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '外呼线路数限制',
  `pro_linereserve` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '保留线路数（低于此线路数不呼）',
  `pro_priority` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '优先级（0-255数字越大优先级越高）',
  `pro_state` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '项目状态（0停止1开始2暂停3企业未启用4企业已欠费）',
  `pro_type` tinyint(3) unsigned NOT NULL DEFAULT '2' COMMENT '呼叫类型（0非自动外呼1外呼转坐席2外呼通知）',
  `pro_context` varchar(64) NOT NULL COMMENT '接通流程',
  `pro_exten` varchar(64) NOT NULL COMMENT '接通流程',
  `pro_ctimeout` tinyint(3) unsigned NOT NULL DEFAULT '45' COMMENT '外呼超时时间',
  `pro_queid` int(10) NOT NULL DEFAULT '0' COMMENT '外呼转技能组ID',
  `pro_cusflag` int(10) unsigned NOT NULL DEFAULT '8' COMMENT '功能标志',
  `pro_maxrate` float NOT NULL COMMENT '最大呼叫比例',
  `pro_channel` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '通道组',
  `recall_times` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '重呼次数',
  `recall_interva` int(10) unsigned NOT NULL DEFAULT '1' COMMENT '重呼间隔（默认是1小时，选项是半小时、1小时、2小时、24小时）',
  `user_id` int(11) NOT NULL COMMENT '创建人id',
  `user_name` varchar(45) NOT NULL COMMENT '创建人姓名',
  `pro_create_time` int(11) NOT NULL,
  `pro_mode` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '任务模式（0普通外呼，一个任务播放同一个语音1高级模式，任务中每个号码可以自定义语音）',
  `survey_id` int(11) NOT NULL DEFAULT '0' COMMENT '问卷ID',
  `callConfirm` tinyint(1) DEFAULT '0' COMMENT '通话确认',
  `syncProject` tinyint(1) DEFAULT '0' COMMENT '修改项目客户数据',
  `checkClientDuplicate` tinyint(1) DEFAULT '0' COMMENT '与CRM客户查重',
  `relevanceClient` tinyint(1) DEFAULT '0' COMMENT '关联CRM客户信息',
  `syncClient` tinyint(1) DEFAULT '0' COMMENT '同步修改CRM客户数据',
  `contact_result` varchar(100) DEFAULT '' COMMENT '联系结果以 , 分割',
  PRIMARY KEY (`pro_id`),
  KEY `pro_state` (`pro_state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='外呼任务表';

CREATE TABLE `est_project_client` (
  `pro_id` int(11) NOT NULL DEFAULT '0' COMMENT '项目ID',
  `task_id` int(11) NOT NULL AUTO_INCREMENT,
  `pro_type` tinyint(1) DEFAULT '0' COMMENT '呼叫方式 1自动外呼0手动外呼',
  `impt_type` int(1) NOT NULL COMMENT '导入类型 （1.文件导入|2.客户表导入）',
  `relevant_type` int(1) NOT NULL COMMENT '关联客户类型 （导入时关联|外呼时关联）',
  `relevant_cle_id` int(11) NOT NULL COMMENT '关联客户ID',
  `info_id` int(11) NOT NULL COMMENT '问卷答案ID',
  `allot_occupy_user` int(11) NOT NULL COMMENT '调配占有人',
  `allot_time` datetime NOT NULL COMMENT '调配时间',
  `allot_user` int(11) NOT NULL COMMENT '调配人',
  `on` int(1) NOT NULL COMMENT '呼叫是否接通过 用于报表统计 只要产生过一次呼通则此值为1 之后此值不变',
  `transfer_cle_id` int(11) DEFAULT NULL COMMENT '转化客户ID',
  `task_load_user_id` int(11) NOT NULL DEFAULT '0' COMMENT '占有人  0默认',
  `user_id` int(11) NOT NULL COMMENT '处理人',
  `save_time` int(11) NOT NULL COMMENT '处理人保存时间',
  `called_times` int(11) NOT NULL DEFAULT '0' COMMENT '已呼叫次数',
  `contact_result` varchar(20) DEFAULT NULL COMMENT '联系结果：成功，呼损，未呼通，其他',
  `task_num` varchar(20) NOT NULL COMMENT '外呼号码',
  `impt_id` int(11) NOT NULL DEFAULT '0' COMMENT '批次号',
  `insert_date` date DEFAULT NULL COMMENT '数据导入日期',
  `insert_time` datetime DEFAULT NULL COMMENT '数据导入时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `cle_name` varchar(50) NOT NULL DEFAULT '' COMMENT '客户姓名【客户信息】',
  `cle_pingyin` varchar(50) NOT NULL DEFAULT '' COMMENT '客户名称拼音【客户信息】',
  `cle_dial_number` int(11) NOT NULL DEFAULT '0' COMMENT '通话次数（拨打次数）',
  `cle_phone` varchar(20) NOT NULL DEFAULT '' COMMENT '客户电话【客户信息】',
  `cle_phone2` varchar(20) NOT NULL DEFAULT '' COMMENT '办公电话',
  `cle_phone3` varchar(20) NOT NULL DEFAULT '' COMMENT '其他电话',
  `cle_address` varchar(100) NOT NULL DEFAULT '' COMMENT '详细地址【客户信息】',
  `cle_info_source` varchar(20) NOT NULL DEFAULT '' COMMENT '信息来源【客户信息】',
  `cle_stage` varchar(20) NOT NULL DEFAULT '' COMMENT '客户阶段（数据字典配置）【客户信息】',
  `cle_last_stage` varchar(255) NOT NULL DEFAULT '' COMMENT '上一次的客户阶段',
  `cle_stage_change_time` date NOT NULL COMMENT '客户阶段改变时间',
  `cle_recede` tinyint(4) NOT NULL DEFAULT '0' COMMENT '退阶标记：1退阶；当阶段后退时变为1，前进时为0',
  `cle_if_increment` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否为新增量：0否，1是',
  `cle_stat` varchar(20) NOT NULL COMMENT '客户状态：未拨打、有效、无效、未呼通、号码错误【客户信息】',
  `cle_remark` text COMMENT '备注【客户信息】',
  `cle_1` varchar(50) NOT NULL DEFAULT '' COMMENT '配置字段1【客户信息】',
  `cle_2` varchar(50) NOT NULL DEFAULT '' COMMENT '配置字段2【客户信息】',
  `cle_3` varchar(50) NOT NULL DEFAULT '' COMMENT '配置字段3【客户信息】',
  `cle_4` varchar(50) NOT NULL DEFAULT '' COMMENT '配置字段4【客户信息】',
  `cle_5` varchar(50) NOT NULL DEFAULT '' COMMENT '配置字段5【客户信息】',
  `cle_6` varchar(50) NOT NULL DEFAULT '' COMMENT '配置字段6【客户信息】',
  `cle_7` varchar(50) NOT NULL DEFAULT '' COMMENT '配置字段7【客户信息】',
  `cle_8` varchar(50) NOT NULL DEFAULT '' COMMENT '配置字段8【客户信息】',
  `cle_9` varchar(50) NOT NULL DEFAULT '' COMMENT '配置字段9【客户信息】',
  `cle_10` varchar(50) NOT NULL DEFAULT '' COMMENT '配置字段10【客户信息】',
  `cle_11` varchar(50) NOT NULL DEFAULT '' COMMENT '配置字段11【客户信息】',
  `cle_12` varchar(50) NOT NULL DEFAULT '' COMMENT '配置字段12【客户信息】',
  `cle_13` varchar(50) NOT NULL DEFAULT '',
  `cle_14` varchar(50) NOT NULL DEFAULT '',
  `cle_15` varchar(50) NOT NULL DEFAULT '',
  `cle_16` varchar(50) NOT NULL DEFAULT '',
  `cle_17` varchar(50) NOT NULL DEFAULT '',
  `cle_18` varchar(50) NOT NULL DEFAULT '',
  `cle_19` varchar(50) NOT NULL DEFAULT '',
  `cle_20` varchar(50) NOT NULL DEFAULT '',
  `cle_21` varchar(50) NOT NULL DEFAULT '',
  `cle_22` varchar(50) NOT NULL DEFAULT '',
  `cle_province_id` int(11) NOT NULL COMMENT '省id',
  `cle_province_name` varchar(20) NOT NULL DEFAULT '' COMMENT '省 ',
  `cle_city_id` int(11) NOT NULL COMMENT '市id',
  `cle_city_name` varchar(20) NOT NULL DEFAULT '' COMMENT '市',
  `data_source` varchar(20) NOT NULL DEFAULT '' COMMENT '数据来源',
  `contact_content` text COMMENT '下次联系内容',
  `contact_time` datetime DEFAULT NULL COMMENT '下次联系时间',
  PRIMARY KEY (`task_id`),
  KEY `cle_phone` (`cle_phone`),
  KEY `cle_name` (`cle_name`),
  KEY `cle_pingyin` (`cle_pingyin`),
  KEY `insert_date` (`insert_date`),
  KEY `idx_pro_id` (`pro_id`),
  KEY `idx_impt_id` (`impt_id`),
  KEY `idx_data_source` (`data_source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='客户信息表';

CREATE TABLE `est_project_contact_record` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pro_id` int(11) DEFAULT NULL COMMENT '项目ID',
  `task_id` int(11) DEFAULT NULL COMMENT '任务ID',
  `call_id` varchar(32) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL COMMENT '联系人ID',
  `contact_type` varchar(255) DEFAULT NULL COMMENT '通话类型',
  `contact_content` text COMMENT '联系内容',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='项目联系记录表';

CREATE TABLE `est_project_ivrs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pro_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '任务id',
  `ivr_file` text NOT NULL COMMENT '流程信息',
  PRIMARY KEY (`id`),
  KEY `pro_id` (`pro_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='任务对应的IVR表';

CREATE TABLE `est_project_phones` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `pro_id` int(11) NOT NULL COMMENT '项目ID',
  `phone_type` tinyint(1) NOT NULL COMMENT '外呼显示方式 2代表普通显示 3代表轮循显示',
  `phones` text NOT NULL COMMENT '外呼显示号码以，分隔',
  PRIMARY KEY (`id`),
  KEY `pro_id` (`pro_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE `est_project_result` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `task_id` int(11) NOT NULL DEFAULT '0' COMMENT '任务ID',
  `pro_id` int(11) NOT NULL DEFAULT '0' COMMENT '项目ID',
  `impt_id` int(11) NOT NULL DEFAULT '0' COMMENT '批次号',
  `call_id` varchar(32) NOT NULL DEFAULT '' COMMENT '呼叫ID',
  `cle_name` varchar(50) NOT NULL DEFAULT '' COMMENT '客户姓名【客户信息】',
  `task_num` varchar(20) NOT NULL COMMENT '外呼号码',
  `task_state` tinyint(4) NOT NULL DEFAULT '0' COMMENT '号码状态（0-未呼叫 1-接通坐席2-未呼通3-接通未转坐席8-临时占用9-呼叫中10-失效）',
  `task_result` tinyint(4) NOT NULL COMMENT '呼叫结果（0接通其他未接通）',
  `contact_result` varchar(20) DEFAULT NULL COMMENT '联系结果：成功，呼损，未呼通，其他',
  `task_cusresult` varchar(20) NOT NULL COMMENT '业务按键',
  `start_time` int(11) NOT NULL DEFAULT '0' COMMENT '开始时间',
  `start_date` date DEFAULT NULL COMMENT '开始时间',
  `begin_time` datetime DEFAULT NULL,
  `begin_hour` int(2) DEFAULT '0' COMMENT '小时',
  `ans_time` int(11) NOT NULL DEFAULT '0' COMMENT '应答时间',
  `end_time` int(11) NOT NULL DEFAULT '0' COMMENT '结束时间',
  `conn_secs` int(10) unsigned NOT NULL COMMENT '通话时长',
  `data_source` varchar(20) NOT NULL DEFAULT '' COMMENT '数据来源',
  `is_adapter` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否是转电话（0不是，1是）',
  `is_transfer` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否转化为客户（0未转化，1转化）',
  `task_load_user_id` int(11) NOT NULL DEFAULT '0' COMMENT '占有人  0默认',
  `user_id` int(11) NOT NULL COMMENT '处理人',
  `on` int(1) NOT NULL COMMENT '呼叫是否接通过 用于报表统计 只要产生过一次呼通则此值为1 之后此值不变',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `pro_id` (`pro_id`,`task_state`,`start_time`),
  KEY `call_id` (`call_id`),
  KEY `task_result` (`task_result`),
  KEY `task_state` (`task_state`),
  KEY `start_time` (`start_time`),
  KEY `idx_data_source` (`data_source`),
  KEY `idx_task_state` (`task_state`),
  KEY `idx_task_result` (`task_result`),
  KEY `idx_start_date` (`start_date`),
  KEY `idx_task_load_uid` (`task_load_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='外呼任务数据表';

CREATE TABLE `est_project_slot` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pro_id` int(11) NOT NULL DEFAULT '0' COMMENT '任务ID',
  `weeks` varchar(15) NOT NULL COMMENT '星期（多个星期之间#分隔）',
  `start_time` time NOT NULL COMMENT '开始时间',
  `end_time` time NOT NULL COMMENT '结束时间',
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  PRIMARY KEY (`id`),
  KEY `pro_id` (`pro_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='外呼任务呼叫时间段';

CREATE TABLE `est_project_task` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `task_id` int(11) NOT NULL,
  `pro_id` int(11) NOT NULL DEFAULT '0' COMMENT '项目ID',
  `task_num` varchar(20) NOT NULL COMMENT '外呼号码',
  `is_recall` int(1) NOT NULL DEFAULT '0' COMMENT '是否在次呼叫标识  2|0 呼 1不呼',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `called_times` int(11) NOT NULL DEFAULT '0' COMMENT '已呼叫次数',
  `priority` tinyint(4) NOT NULL DEFAULT '0' COMMENT '优先级',
  `call_time` datetime NOT NULL COMMENT '呼叫时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='外呼表';

CREATE TABLE `est_clear_error_data` (
  `log_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '数据ID，主键，自增',
  `impt_id` int(11) NOT NULL DEFAULT '0' COMMENT '导入批次号',
  `name` varchar(50) NOT NULL COMMENT '客户姓名【客户信息】',
  `phone` varchar(20) NOT NULL COMMENT '客户电话【客户信息】',
  `reson` varchar(60) NOT NULL COMMENT '异常原因（文件上传失败，文件损坏，文件过大，数据异常）',
  PRIMARY KEY (`log_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='记录导入过程中的不合法数据';

CREATE TABLE `est_import_log` (
  `impt_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键，自增；导入批次号',
  `impt_total` int(11) NOT NULL DEFAULT '0' COMMENT '本次导入总数',
  `impt_state` tinyint(1) NOT NULL DEFAULT '0' COMMENT '导入状态：0失败，1成功',
  `impt_success` int(11) NOT NULL DEFAULT '0' COMMENT '导入成功数',
  `impt_fail` int(11) NOT NULL DEFAULT '0' COMMENT '导入失败的数量',
  `impt_time` int(11) NOT NULL DEFAULT '0' COMMENT '导入时间',
  `user_id` int(11) NOT NULL DEFAULT '0' COMMENT '操作人ID',
  `dept_id` int(11) NOT NULL DEFAULT '0' COMMENT '部门ID',
  `impt_type` int(11) NOT NULL DEFAULT '0' COMMENT '导入类型  0默认 1客户导入 2产品导入',
  `user_name` varchar(64) NOT NULL COMMENT '操作人名称',
  `pro_id` int(11) DEFAULT '0' COMMENT '任务ID',
  `data_source` varchar(64) DEFAULT NULL COMMENT '数据来源',
  `impt_way` tinyint(1) DEFAULT '-1' COMMENT '导入方式 0 excel导入  1 客户导入',
  PRIMARY KEY (`impt_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='数据导入日志';

ALTER TABLE `est_project` MODIFY COLUMN `pro_caller` text DEFAULT NULL COMMENT '外呼主叫显示';

CREATE  VIEW `PROJECT_RESULT_END` AS select `est_project_result`.`id` AS `result_id`,`est_project_result`.`pro_id` AS `pro_id`,`est_project_result`.`task_id` AS `task_id`,`est_project_result`.`begin_time` AS `begin_time`,`est_project_result`.`conn_secs` AS `conn_secs`,`est_project_result`.`task_cusresult` AS `task_cusresult`,`est_project_result`.`update_time` AS `update_time` from `est_project_result` where concat(`est_project_result`.`task_id`,'-',`est_project_result`.`id`) in (select concat(`est_project_result`.`task_id`,'-',max(`est_project_result`.`id`)) from `est_project_result` group by `est_project_result`.`task_id`) ;
