apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ceph-db
provisioner: kubernetes.io/rbd
parameters:
  monitors: 192.168.78.110:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: default
  pool: k8s
  userId: admin
  userSecretName: ceph-secret
