apiVersion: v1
kind: Service
metadata:
  namespace: basic-app
  name: elastic-head
  labels:
    app: elastic-head
spec:
  ports:
  - port: 9100
    targetPort: 9100
  selector:
    app: elastic-head
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: basic-app
  name: elastic-head
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elastic-head
    spec:
      containers:
      - image: mobz/elasticsearch-head:5-alpine
        name: elastic
        command: ["/bin/sh"]
        args: ["-c", "sed -i 's/localhost/elastic-cluster/g' /usr/src/app/_site/app.js; node_modules/http-server/bin/http-server _site -p 9100;"]
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9100
        livenessProbe:
          tcpSocket:
            port: 9100
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: timezone-config
          mountPath: /etc/localtime
      volumes:
      - name: timezone-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai