ALTER TABLE est_cdr MODIFY COLUMN cle_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '客户ID';
ALTER TABLE est_cdr ADD COLUMN is_crm TINYINT(2) NOT NULL DEFAULT 0 COMMENT '是否为新CRM';
ALTER TABLE est_lost_cdr MODIFY COLUMN cle_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '客户ID';
ALTER TABLE est_lost_cdr ADD COLUMN is_crm TINYINT(2) NOT NULL DEFAULT 0 COMMENT '是否为新CRM';
ALTER TABLE `est_knowledge_context` ADD COLUMN `update_time` datetime NOT NULL COMMENT '更新时间',ADD COLUMN `update_uid` INT NOT NULL COMMENT '更新人',ADD COLUMN `valid` TINYINT (4) NOT NULL DEFAULT '1' COMMENT '1永久有效2自定义有效时间',ADD COLUMN `valid_date_start` VARCHAR (20) NOT NULL DEFAULT '' COMMENT '自定义有效开始时间',ADD COLUMN `valid_date_end` VARCHAR (20) NOT NULL DEFAULT '' COMMENT '自定义有效结束时间';
ALTER TABLE `est_users` MODIFY COLUMN `user_outcaller_num` text NOT NULL COMMENT '指定的外呼主叫';