apiVersion: v1
kind: Namespace
metadata:
  name: basic-app
---
apiVersion: v1
kind: Secret
metadata:
  namespace: basic-app
  name: ceph-secret
type: "kubernetes.io/rbd"
data:
  key: QVFDVWdZcGJ1QVRWS0JBQWZPeDNlNWFIM1A0T3Z1T1l6M2prYWc9PQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-config
  namespace: basic-app
data:
  elasticsearch.yml: |
    cluster.name: elastic
    path.data: /usr/local/elasticsearch-5.3.3/data
    path.logs: /usr/local/elasticsearch-5.3.3/logs
    network.host: 0.0.0.0
    http.port: 9200
    discovery.zen.ping.unicast.hosts: ["elastic-cluster"]
    discovery.zen.minimum_master_nodes: 2
    http.cors.enabled: true
    http.cors.allow-origin: "*"
---
kind: Service
apiVersion: v1
metadata:
  namespace: basic-app
  name: elastic-cluster
  labels:
    app: elastic
spec:
  ports:
    - name: business
      port: 9200
      targetPort: 9200
    - name: sync
      port: 9300
      targetPort: 9300
  selector:
    app: elastic
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-config
  namespace: basic-app
data:
  elasticsearch.yml: |
    cluster.name: elastic
    node.name: node-1
    path.data: /usr/local/elasticsearch-5.3.3/data
    path.logs: /usr/local/elasticsearch-5.3.3/logs
    network.host: 0.0.0.0
    http.port: 9200
    discovery.zen.ping.unicast.hosts: ["elastic-cluster"]
    discovery.zen.minimum_master_nodes: 2
    http.cors.enabled: true
    http.cors.allow-origin: "*"
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: basic-app
  name: elastic-cluster
  labels:
    app: elastic
spec:
  serviceName: elasticsearch
  replicas: 3
  template:
    metadata:
      labels:
        app: elastic
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: elastic
        image: 144.202.127.156/library/elasticsearch:5.3.3
        command: ["sh", "-c", "chown  elastic:elastic -R /usr/local/elasticsearch-5.3.3/;
                             sudo -H -u elastic sh /usr/local/elasticsearch-5.3.3/bin/elasticsearch"]
        resources:
          limits:
            cpu: 2
            memory: 4G
          requests:
            cpu: 1
            memory: 2G
        volumeMounts:
        - name: data
          mountPath: /usr/local/elasticsearch-5.3.3/data
        - name: elastic-config
          mountPath: /usr/local/elasticsearch-5.3.3/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: timezone-config
          mountPath: /etc/localtime
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 9200
        - containerPort: 9300
        livenessProbe:
          tcpSocket:
            port: 9200
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: elastic-config
        configMap:
          name: elastic-config
          items:
          - key: elasticsearch.yml
            path: elasticsearch.yml
      - name: timezone-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.beta.kubernetes.io/storage-class: "ceph-db"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Gi