apiVersion: v1
kind: Namespace
metadata:
  name: elk
---
apiVersion: v1
kind: Secret
metadata:
  namespace: elk
  name: ceph-secret
type: "kubernetes.io/rbd"
data:
  key: QVFEYmVRTmJZQ1B4TFJBQUg0QS9Tb01NZjF6NHB3L0p1Y3ZUQnc9PQ==
---
kind: Service
apiVersion: v1
metadata:
  namespace: elk
  labels:
    app: elk-elastic
  name: elk-es
spec:
  type: NodePort
  ports:
    - name: business
      port: 9200
      targetPort: 9200
    - name: sync
      port: 9300
      targetPort: 9300
  selector:
    app: elk-elastic
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: elk
  name: elk-es
  labels:
    app: elk-elastic
spec:
  serviceName: elasticsearch
  replicas: 2
  selector:
    matchLabels:
      app: elk-elastic
  template:
    metadata:
      labels:
        app: elk-elastic
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: elastic
        image: 144.202.127.156/library/elasticsearch:5.3.3
        volumeMounts:
        - name: data
          mountPath: /usr/local/elasticsearch-5.3.3/data
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 9200
        - containerPort: 9300
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.beta.kubernetes.io/storage-class: "ceph-db"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi