apiVersion: v1
kind: Namespace
metadata:
  name: basic-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-config
  namespace: basic-app
data:
  logstash.config: |
    cluster.name: icsoc
    node.name: node-1
    path.data: /usr/local/elasticsearch-2.4.6/data
    path.logs: /usr/local/elasticsearch-2.4.6/logs
    ES_HEAP_SIZE: 2g
    network.host: 0.0.0.0
    http.port: 9200
    discovery.zen.ping.unicast.hosts: ["elasticsearch"]
    discovery.zen.minimum_master_nodes: 2
---
kind: Service
apiVersion: v1
metadata:
  labels:
    elastic-app: elasticsearch
  name: elasticsearch
  namespace: basic-app
spec:
  type: NodePort
  ports:
    - name: business
      port: 9200
      targetPort: 9200
      nodePort: 32100
    - name: sync
      port: 9300
      targetPort: 9300
  selector:
    app: elasticsearch
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
  namespace: basic-app
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
        terminationGracePeriodSeconds: 10
        containers:
        - name: elasticsearch
          image: 10.168.1.200/library/elasticsearch:2.4
          volumeMounts:
          - name: elasticsearch-config
            mountPath: /usr/local/elasticsearch-2.4.6/config
          - name: data
            mountPath: /usr/local/elasticsearch-2.4.6/data
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          ports:
          - containerPort: 9200
          - containerPort: 9300
        volumes:
        - name: elasticsearch-config
          configMap:
            name: elastic-config
        imagePullSecrets:
        - name: regsecret
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.beta.kubernetes.io/storage-class: "ceph-db"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi


