kind: Service
apiVersion: v1
metadata:
  labels:
    app: elastic-exporter
  name: elastic-export
  namespace: monitor
spec:
  type: NodePort
  ports:
    - name: business
      port: 9108
      targetPort: 9108
  selector:
    app: elastic-exporter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elastic-exporter
  namespace: monitor
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elastic-exporter
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - command:
        - /bin/elasticsearch_exporter
        - -es.uri=http://elk-es.elk:9200
        - -es.all=true
        image: justwatch/elasticsearch_exporter:1.0.1
        securityContext:
          capabilities:
            drop:
            - SETPCAP
            - MKNOD
            - AUDIT_WRITE
            - CHOWN
            - NET_RAW
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - SETGID
            - SETUID
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: 9108
          initialDelaySeconds: 30
          timeoutSeconds: 10
        name: elastic-exporter
        ports:
        - containerPort: 9108
        readinessProbe:
          httpGet:
            path: /health
            port: 9108
          initialDelaySeconds: 10
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 25m
            memory: 64Mi
      restartPolicy: Always
